on: [push, pull_request]

name: Submit Card Shuffle Metadata To psclaude ReARM

jobs:
  submit-mafia-test-harness:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    name: Submit mafia-test-harness Metadata
    runs-on: ubuntu-latest
    concurrency:
      group: submit-mafia-test-harness-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup ReARM CLI
        uses: relizaio/rearm-actions/setup-cli@b243664866fed080d03837b299cdcd796e7e2218

      - name: Initialize ReARM Release
        id: init
        uses: relizaio/rearm-actions/initialize@b243664866fed080d03837b299cdcd796e7e2218
        with:
          rearm_api_key: ${{ secrets.REARM_API_KEY }}
          rearm_api_id: ${{ secrets.REARM_API_ID }}
          rearm_api_url: https://psclaude.rearmhq.com
          repo_path: test-harness
          create_component: 'true'

      - name: Generate npm SBOM
        if: steps.init.outputs.do_build == 'true'
        working-directory: test-harness
        run: |
          npm install --global @cyclonedx/cyclonedx-npm@4.2.1 --ignore-scripts
          npm ci --ignore-scripts
          cyclonedx-npm --flatten-components > fs.cdx.bom.json
          du -h fs.cdx.bom.json

      - name: Submit release metadata to ReARM
        if: steps.init.outputs.do_build == 'true'
        working-directory: test-harness
        env:
          REARM_API_ID: ${{ secrets.REARM_API_ID }}
          REARM_API_KEY: ${{ secrets.REARM_API_KEY }}
        run: |
          set -e
          rearm_branch_name="${{ github.head_ref || github.ref_name }}"
          scearts='[{"bomFormat":"CYCLONEDX","type":"BOM","filePath":"./fs.cdx.bom.json"}]'
          rearm addrelease \
            --apikeyid "$REARM_API_ID" \
            --apikey "$REARM_API_KEY" \
            -u https://psclaude.rearmhq.com \
            -b "$rearm_branch_name" \
            -v "${{ steps.init.outputs.full_version }}" \
            --lifecycle ASSEMBLED \
            --vcsuri "${{ github.server_url }}/${{ github.repository }}" \
            --repo-path test-harness \
            --commit "${{ steps.init.outputs.sce_commit }}" \
            --commitmessage "${{ steps.init.outputs.sce_commit_message }}" \
            --date "${{ steps.init.outputs.sce_commit_date }}" \
            --commits "${{ steps.init.outputs.commit_list }}" \
            --datestart "${{ steps.init.outputs.build_start }}" \
            --dateend "$(date -Iseconds)" \
            --scearts "$scearts"
